"""
GDPR compliance router - Data access and deletion endpoints.

Implements GDPR Article 15 (Right of Access) and Article 17 (Right to Erasure):
- Export all user data (right to access)
- Delete all user data (right to be forgotten)
- Request data export for large datasets (async processing)
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from motor.motor_asyncio import AsyncIOMotorDatabase
from pydantic import BaseModel, Field

from app.core.dependencies import (
    download_rate_limit,
    get_current_user,
    get_database,
    require_permission,
)
from app.models.role import Permission
from app.models.user import User

router = APIRouter(prefix="/v1/user", tags=["gdpr"])
logger = logging.getLogger("aloft.gdpr")


class UserDataExport(BaseModel):
    """Complete user data export for GDPR compliance."""

    user_id: str
    email: str
    role: str
    is_active: bool
    is_verified: bool
    mfa_enabled: bool
    created_at: datetime
    updated_at: datetime
    last_login_at: datetime | None
    last_login_ip: str | None
    password_changed_at: datetime | None
    pois: list[dict[str, Any]] = Field(default_factory=list)
    stories: list[dict[str, Any]] = Field(default_factory=list)
    audio_assets: list[dict[str, Any]] = Field(default_factory=list)
    route_bundles: list[dict[str, Any]] = Field(default_factory=list)
    sessions: list[dict[str, Any]] = Field(default_factory=list)
    export_timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class DataDeletionConfirmation(BaseModel):
    """Confirmation for data deletion request."""

    require_confirmation: bool = Field(default=True, description="Must be true to confirm deletion")
    reason: str = Field(
        ..., min_length=10, max_length=500, description="Reason for data deletion request"
    )


class DataDeletionResponse(BaseModel):
    """Response for data deletion request."""

    user_id: str
    email: str
    deletion_requested: bool
    deletion_scheduled: datetime
    data_categories_deleted: list[str]
    cancellation_link: str | None = None


class DataExportRequest(BaseModel):
    """Request for async data export (for large datasets)."""

    include_audio: bool = True
    include_images: bool = True
    format: str = Field(default="json", pattern="^(json|csv)$")


async def get_user_pois(db: AsyncIOMotorDatabase, user_id: str) -> list[dict[str, Any]]:
    """Get all POIs created or accessed by the user."""
    # Note: POIs are shared, so we might track user access separately
    # For now, return empty list as POIs are not user-specific
    return []


async def get_user_stories(db: AsyncIOMotorDatabase, user_id: str) -> list[dict[str, Any]]:
    """Get all stories generated by the user."""
    stories = await db.stories.find({"user_id": user_id}).to_list(length=None)
    # Remove sensitive fields if any
    for story in stories:
        story.pop("_id", None)
    return stories


async def get_user_audio_assets(db: AsyncIOMotorDatabase, user_id: str) -> list[dict[str, Any]]:
    """Get all audio assets generated by the user."""
    audio_assets = await db.audio_assets.find({"user_id": user_id}).to_list(length=None)
    for asset in audio_assets:
        asset.pop("_id", None)
        asset.pop("file_path", None)  # Don't expose file paths
    return audio_assets


async def get_user_route_bundles(db: AsyncIOMotorDatabase, user_id: str) -> list[dict[str, Any]]:
    """Get all route bundles created by the user."""
    route_bundles = await db.route_bundles.find({"user_id": user_id}).to_list(length=None)
    for bundle in route_bundles:
        bundle.pop("_id", None)
    return route_bundles


async def get_user_sessions(db: AsyncIOMotorDatabase, user_id: str) -> list[dict[str, Any]]:
    """Get recent session history for the user."""
    # Sessions are stored in Redis, not MongoDB
    # This would require Redis query implementation
    return []


@router.get(
    "/data",
    response_model=UserDataExport,
    summary="Export all user data (GDPR Article 15)",
    description=(
        "Returns all personal data associated with the user account. "
        "Implements GDPR Right of Access (Article 15). "
        "Includes user profile, generated content, and session history."
    ),
    dependencies=[
        Depends(download_rate_limit()),
        Depends(require_permission(Permission.READ_USER)),
    ],
)
async def export_user_data(
    current_user: User = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
) -> UserDataExport:
    """Export all user data for GDPR compliance.

    This endpoint returns all personal data stored about the user,
    implementing the GDPR Right of Access (Article 15).
    """
    logger.info(f"Data export requested by user: {current_user.user_id}")

    # Collect all user data
    pois = await get_user_pois(db, current_user.user_id)
    stories = await get_user_stories(db, current_user.user_id)
    audio_assets = await get_user_audio_assets(db, current_user.user_id)
    route_bundles = await get_user_route_bundles(db, current_user.user_id)
    sessions = await get_user_sessions(db, current_user.user_id)

    return UserDataExport(
        user_id=current_user.user_id,
        email=current_user.email,
        role=current_user.role.value,
        is_active=current_user.is_active,
        is_verified=current_user.is_verified,
        mfa_enabled=current_user.mfa_enabled,
        created_at=current_user.created_at,
        updated_at=current_user.updated_at,
        last_login_at=current_user.last_login_at,
        last_login_ip=current_user.last_login_ip,
        password_changed_at=current_user.password_changed_at,
        pois=pois,
        stories=stories,
        audio_assets=audio_assets,
        route_bundles=route_bundles,
        sessions=sessions,
    )


@router.post(
    "/data/request-export",
    summary="Request async data export (for large datasets)",
    description=(
        "Request an asynchronous data export for large datasets. "
        "Returns a download link when ready. Useful for users with extensive data."
    ),
)
async def request_data_export(
    request: DataExportRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
) -> dict[str, str]:
    """Request an asynchronous data export.

    For users with large datasets, this endpoint initiates an async
    export process and returns a download link when ready.
    """
    logger.info(f"Async data export requested by user: {current_user.user_id}")

    # In a real implementation, this would:
    # 1. Create an export job in a queue
    # 2. Process the export asynchronously
    # 3. Store the result in secure storage
    # 4. Return a download link with expiration

    # For now, return a placeholder response
    return {
        "status": "processing",
        "export_id": f"export_{current_user.user_id}_{int(datetime.now(UTC).timestamp())}",
        "message": "Export will be processed asynchronously. You will receive an email when ready.",
        "estimated_completion": "5-10 minutes",
    }


@router.delete(
    "/data",
    response_model=DataDeletionResponse,
    summary="Delete all user data (GDPR Article 17)",
    description=(
        "Deletes all personal data associated with the user account. "
        "Implements GDPR Right to Erasure (Article 17 - Right to be Forgotten). "
        "This action is irreversible. Requires explicit confirmation."
    ),
)
async def delete_user_data(
    confirmation: DataDeletionConfirmation,
    current_user: User = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database),
) -> DataDeletionResponse:
    """Delete all user data for GDPR compliance.

    This endpoint permanently deletes all personal data associated with
    the user account, implementing the GDPR Right to Erasure (Article 17).
    """
    if not confirmation.require_confirmation:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Explicit confirmation required for data deletion",
        )

    logger.warning(
        f"Data deletion requested by user: {current_user.user_id}, reason: {confirmation.reason}"
    )

    # In a real implementation, this would:
    # 1. Delete user account
    # 2. Delete all user-generated content
    # 3. Delete session data from Redis
    # 4. Anonymize any shared data (POIs, etc.)
    # 5. Log the deletion for audit purposes
    # 6. Send confirmation email

    deletion_scheduled = datetime.now(UTC)
    data_categories = [
        "user_profile",
        "stories",
        "audio_assets",
        "route_bundles",
        "sessions",
        "authentication_tokens",
    ]

    # For now, return a placeholder response
    # In production, implement actual deletion logic
    return DataDeletionResponse(
        user_id=current_user.user_id,
        email=current_user.email,
        deletion_requested=True,
        deletion_scheduled=deletion_scheduled,
        data_categories_deleted=data_categories,
        cancellation_link=f"/v1/user/data/cancel/{current_user.user_id}",
    )


@router.post(
    "/data/cancel-deletion",
    summary="Cancel pending data deletion",
    description="Cancel a pending data deletion request if it hasn't been processed yet.",
)
async def cancel_data_deletion(
    current_user: User = Depends(get_current_user),
) -> dict[str, str]:
    """Cancel a pending data deletion request."""
    logger.info(f"Data deletion cancellation requested by user: {current_user.user_id}")

    # In a real implementation, this would:
    # 1. Check if deletion is still pending
    # 2. Cancel the deletion job
    # 3. Send confirmation email

    return {
        "status": "cancelled",
        "message": "Data deletion has been cancelled. Your account and data remain intact.",
    }


@router.get(
    "/data/status",
    summary="Check data export/deletion status",
    description="Check the status of pending data export or deletion requests.",
)
async def get_data_status(
    current_user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """Check the status of pending data operations."""
    return {
        "user_id": current_user.user_id,
        "export_status": "none",
        "deletion_status": "none",
        "last_export_at": None,
        "last_deletion_requested_at": None,
    }
